[package]
name = "gnn"
version = "0.1.0"
edition = "2021"

[[example]]
name = "aplusb"

[lib]
name = "gnn"
path = "src/lib.rs"

[profile.dev]
opt-level = 1

[dependencies]
rand = "0.8.5"
rayon = "1.8.0"